### ISSUE TITLE
"The redactor has some trouble on old files."

### ISSUE THREAD

**Issue by divergentdave** [JoshData/crs-reports-website#10]
This is regarding https://github.com/JoshData/crs-reports-website/blob/ae193cee52e57860ed7e50fbeca3cc5fed82a693/process_incoming.py#L450. The good news is that there are only three unique exceptions for all the PDFs. (total of 52 problem files) See below for representative tracebacks. These are all issues with dependencies (two in pdfrw and one in pdf-redactor) but I figured it would be good to track it here.

```
AssertionError while reading /mnt/Bluffdale/crs-reports/files/20020204_RL31011_ccf3877c3c53f86c04598b4b333c5f4230ee3c3c.pdf
Traceback (most recent call last):
  File "./smoketest.py", line 40, in smoke_test_file
    pdf_redactor.redactor(options)
  File "/home/david/pdf-redactor/pdf_redactor.py", line 94, in redactor
    text_layer = build_text_layer(document, options)
  File "/home/david/pdf-redactor/pdf_redactor.py", line 393, in build_text_layer
    token = make_mutable_string_token(token)
  File "/home/david/pdf-redactor/pdf_redactor.py", line 380, in make_mutable_string_token
    token = TextToken(token.decode(), current_font)
  File "/home/david/.virtualenvs/pdf-redactor/lib/python3.4/site-packages/pdfrw/objects/pdfstring.py", line 67, in decode
    return self.decode_hex(remap, twobytes)
  File "/home/david/.virtualenvs/pdf-redactor/lib/python3.4/site-packages/pdfrw/objects/pdfstring.py", line 59, in decode_hex
    ''.join(other) == '<>'), self
AssertionError: <
```

```
AssertionError while reading /mnt/Bluffdale/crs-reports/files/19971209_97-201_9ab84e5aee0604c6a644bdeb748802036b22eefc.pdf
Traceback (most recent call last):
  File "./smoketest.py", line 40, in smoke_test_file
    pdf_redactor.redactor(options)
  File "/home/david/pdf-redactor/pdf_redactor.py", line 94, in redactor
    text_layer = build_text_layer(document, options)
  File "/home/david/pdf-redactor/pdf_redactor.py", line 393, in build_text_layer
    token = make_mutable_string_token(token)
  File "/home/david/pdf-redactor/pdf_redactor.py", line 380, in make_mutable_string_token
    token = TextToken(token.decode(), current_font)
  File "/home/david/.virtualenvs/pdf-redactor/lib/python3.4/site-packages/pdfrw/objects/pdfstring.py", line 67, in decode
    return self.decode_hex(remap, twobytes)
  File "/home/david/.virtualenvs/pdf-redactor/lib/python3.4/site-packages/pdfrw/objects/pdfstring.py", line 59, in decode_hex
    ''.join(other) == '<>'), self
AssertionError: <>
```

```
IndexError while reading /mnt/Bluffdale/crs-reports/files/20000929_RL30515_9dbf81c728c9b6372e23a9b1280cfbd0a357d93d.pdf
Traceback (most recent call last):
  File "./smoketest.py", line 40, in smoke_test_file
    pdf_redactor.redactor(options)
  File "/home/david/pdf-redactor/pdf_redactor.py", line 94, in redactor
    text_layer = build_text_layer(document, options)
  File "/home/david/pdf-redactor/pdf_redactor.py", line 390, in build_text_layer
    for token in tokenize_streams(content.stream for content in contents):
  File "/home/david/pdf-redactor/pdf_redactor.py", line 265, in tokenize_streams
    constructor, content = stack.pop(-1)
IndexError: pop from empty list
```

**Comment by divergentdave** [comment]
The pdfrw errors are happening because the tokenizer isn't handling inline images, and when the intervening binary data includes a left angle bracket, it tries and fails to parse it as a hex encoded string. I'll put together a minimized test case and open an issue tomorrow.

**Comment by divergentdave** [comment]
See pmaupin/pdfrw#67

**Comment by divergentdave** [comment]
Turns out all of these will have to be fixed in pdf-redactor.

Reference links:
http://stackoverflow.com/questions/39927639/is-it-possible-to-use-libtiff-to-decode-ccitt-encoded-data-when-the-length-is-no
https://issues.apache.org/jira/browse/PDFBOX-2163
